{
    "name": "Analítica de compras",
    "version": "18.0.1.9.4",
    "category": "Inventory/Purchase",
    "summary": "Compras, demanda, recepciones, pagos y crédito de proveedores",
    "author": "Systore",
    "license": "LGPL-3",
    "depends": [
        "purchase_stock",
        "sale_stock",
        "web",
        "purchase_recosteo_importacion",
        "wholesale_allocation",
        "stock_upc_validation",
    ],
    "data": [
        "security/supply_security.xml",
        "security/ir.model.access.csv",
        "views/supply_dashboard_views.xml",
        "views/res_partner_views.xml",
        "views/purchase_order_views.xml",
        "views/stock_warehouse_views.xml",
        "views/supply_dashboard_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "systore_purchase_supply_dashboard/static/src/js/supply_dashboard.js",
            "systore_purchase_supply_dashboard/static/src/xml/supply_dashboard.xml",
            "systore_purchase_supply_dashboard/static/src/scss/supply_dashboard.scss",
        ],
    },
    "application": True,
    "post_init_hook": "post_init_hook",
    "installable": True,
}
