{
    'name': 'Systore · Tablero de operaciones',
    'version': '18.0.1.5.0',
    'summary': 'Recepciones, salidas desde existencias y expediciones por almacén',
    'category': 'Inventory/Inventory',
    'author': 'Systore',
    'license': 'LGPL-3',
    'depends': ['web', 'purchase_stock', 'sale_stock', 'stock_picking_batch',
                'adicional_serial_number', 'stock_upc_validation'],
    'data': [
        'security/ir.model.access.csv',
        'views/stock_warehouse_views.xml',
        'views/purchase_order_views.xml',
        'views/stock_picking_views.xml',
        'views/dashboard_actions.xml',
        'views/guided_operation_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'systore_operations_dashboard/static/src/dashboard.js',
            'systore_operations_dashboard/static/src/dashboard.xml',
            'systore_operations_dashboard/static/src/dashboard.scss',
            'systore_operations_dashboard/static/src/dispatch.js',
            'systore_operations_dashboard/static/src/dispatch.xml',
            'systore_operations_dashboard/static/src/mobile_pick.js',
            'systore_operations_dashboard/static/src/mobile_pick.xml',
            'systore_operations_dashboard/static/src/mobile_pick.scss',
            'systore_operations_dashboard/static/src/mobile_receipt.js',
            'systore_operations_dashboard/static/src/mobile_receipt.xml',
            'systore_operations_dashboard/static/src/mobile_pack.js',
            'systore_operations_dashboard/static/src/mobile_pack.xml',
        ],
    },
    'installable': True,
    'application': True,
}
