{
    'name': 'Stock UPC Validation',
    'version': '18.0.1.14.2',
    'summary': 'Validate UPC/EAN and capture NS/IMEI individually or in bulk on the effective pack step, with optional shipping guide.',
    'author': 'Systore',
    'license': 'LGPL-3',
    'depends': [
        'stock',
        'stock_picking_batch',
        'purchase',
        'delivery',
        'product_multiple_barcodes',
        'adicional_serial_number',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/stock_picking_type_defaults.xml',
        'wizard/stock_receipt_upc_wizard_views.xml',
        'wizard/stock_picking_upc_wizard_views.xml',
        'wizard/stock_pack_tracking_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'views/stock_picking_type_views.xml',
        'views/stock_picking_views.xml',
        'report/stock_upc_batch_summary_report.xml',
        'views/stock_picking_batch_views.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
}
